name: Solar System CI

on:
    push:
    workflow_dispatch: 

env:
    MONGO_URI: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}

jobs:
    unit-testing:
        strategy:
            matrix:
                nodejs-version: [20]
                operating-system: [ubuntu-latest]
        runs-on: ${{ matrix.operating-system }}
        env:
            MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        # container: node:24
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4
            
          - name: List repo file
            run: ls -ltr
        
          - uses: actions/setup-node@v4
            with:
                node-version: ${{ matrix.nodejs-version }}

          - name: Installing Dependencies
            run: npm install --no-audit

          - name: Unit Testing
            run: npm test

          - uses: actions/upload-artifact@v4
            with:
                name: Mocha-Test-Results-${{ matrix.nodejs-version }}-${{ matrix.operating-system }}
                path: test-results.xml

          - name: Publish test results
            uses: EnricoMi/publish-unit-test-result-action@v2.12.0
            if: always()
            with:
                junit_files: test-results.xml
